TEST11

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -83,221 +83,221 @@ jobs:
 
            echo "target=$JSON" >> $GITHUB_OUTPUT
 
-  build:
-    name: Build Kernel with external toolchain
-    needs: determine_targets
-    runs-on: ubuntu-latest
-    strategy:
-       fail-fast: False
-       matrix:
-         target: ${{fromJson(needs.determine_targets.outputs.target)}}
+  # build:
+  #   name: Build Kernel with external toolchain
+  #   needs: determine_targets
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #      fail-fast: False
+  #      matrix:
+  #        target: ${{fromJson(needs.determine_targets.outputs.target)}}
 
-    container: ghcr.io/${{ needs.determine_targets.outputs.owner_lc }}/tools:latest
+  #   container: ghcr.io/${{ needs.determine_targets.outputs.owner_lc }}/tools:latest
 
-    permissions:
-      contents: read
-      packages: read
+  #   permissions:
+  #     contents: read
+  #     packages: read
 
-    steps:
-      - name: Checkout master directory
-        uses: actions/checkout@v3
-        with:
-          path: openwrt
+  #   steps:
+  #     - name: Checkout master directory
+  #       uses: actions/checkout@v3
+  #       with:
+  #         path: openwrt
 
-      - name: Checkout packages feed
-        uses: actions/checkout@v3
-        with:
-          repository: openwrt/packages
-          path: openwrt/feeds/packages
+  #     - name: Checkout packages feed
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: openwrt/packages
+  #         path: openwrt/feeds/packages
 
-      - name: Checkout luci feed
-        uses: actions/checkout@v3
-        with:
-          repository: openwrt/luci
-          path: openwrt/feeds/luci
+  #     - name: Checkout luci feed
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: openwrt/luci
+  #         path: openwrt/feeds/luci
 
-      - name: Checkout routing feed
-        uses: actions/checkout@v3
-        with:
-          repository: openwrt/routing
-          path: openwrt/feeds/routing
+  #     - name: Checkout routing feed
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: openwrt/routing
+  #         path: openwrt/feeds/routing
 
-      - name: Checkout telephony feed
-        uses: actions/checkout@v3
-        with:
-          repository: openwrt/telephony
-          path: openwrt/feeds/telephony
+  #     - name: Checkout telephony feed
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: openwrt/telephony
+  #         path: openwrt/feeds/telephony
 
-      - name: Fix permission
-        run: |
-          chown -R buildbot:buildbot openwrt
+  #     - name: Fix permission
+  #       run: |
+  #         chown -R buildbot:buildbot openwrt
 
-      - name: Initialization environment
-        run: |
-          TARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 1)
-          SUBTARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 2)
-          echo "TARGET=$TARGET" >> "$GITHUB_ENV"
-          echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
+  #     - name: Initialization environment
+  #       run: |
+  #         TARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 1)
+  #         SUBTARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 2)
+  #         echo "TARGET=$TARGET" >> "$GITHUB_ENV"
+  #         echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
 
-      - name: Update & Install feeds
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: |
-          ./scripts/feeds update -a
-          ./scripts/feeds install -a
+  #     - name: Update & Install feeds
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: |
+  #         ./scripts/feeds update -a
+  #         ./scripts/feeds install -a
 
-      - name: Parse toolchain file
-        working-directory: openwrt
-        run: |
-          TOOLCHAIN_STRING="$(curl "https://downloads.cdn.openwrt.org/snapshots/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums" \
-            | grep ".*openwrt-toolchain.*tar.xz")"
-          TOOLCHAIN_FILE=$(echo "$TOOLCHAIN_STRING" | sed -n -e 's/.*\(openwrt-toolchain.*\).tar.xz/\1/p')
-          TOOLCHAIN_SHA256=$(echo "$TOOLCHAIN_STRING" | cut -d ' ' -f 1)
+  #     - name: Parse toolchain file
+  #       working-directory: openwrt
+  #       run: |
+  #         TOOLCHAIN_STRING="$(curl "https://downloads.cdn.openwrt.org/snapshots/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums" \
+  #           | grep ".*openwrt-toolchain.*tar.xz")"
+  #         TOOLCHAIN_FILE=$(echo "$TOOLCHAIN_STRING" | sed -n -e 's/.*\(openwrt-toolchain.*\).tar.xz/\1/p')
+  #         TOOLCHAIN_SHA256=$(echo "$TOOLCHAIN_STRING" | cut -d ' ' -f 1)
 
-          echo "TOOLCHAIN_FILE=$TOOLCHAIN_FILE" >> "$GITHUB_ENV"
-          echo "TOOLCHAIN_SHA256=$TOOLCHAIN_SHA256" >> "$GITHUB_ENV"
+  #         echo "TOOLCHAIN_FILE=$TOOLCHAIN_FILE" >> "$GITHUB_ENV"
+  #         echo "TOOLCHAIN_SHA256=$TOOLCHAIN_SHA256" >> "$GITHUB_ENV"
 
-      - name: Cache external toolchain
-        id: cache-external-toolchain
-        uses: actions/cache@v3
-        with:
-          path: openwrt/${{ env.TOOLCHAIN_FILE }}
-          key: ${{ env.TOOLCHAIN_FILE }}-${{ env.TOOLCHAIN_SHA256 }}
+  #     - name: Cache external toolchain
+  #       id: cache-external-toolchain
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: openwrt/${{ env.TOOLCHAIN_FILE }}
+  #         key: ${{ env.TOOLCHAIN_FILE }}-${{ env.TOOLCHAIN_SHA256 }}
 
-      - name: Cache ccache
-        uses: actions/cache@v3
-        with:
-          path: openwrt/.ccache
-          key: ccache-kernel-${{ env.TARGET }}/${{ env.SUBTARGET }}-${{ needs.determine_targets.outputs.ccache_hash }}
-          restore-keys: |
-            ccache-kernel-${{ env.TARGET }}/${{ env.SUBTARGET }}-
+  #     - name: Cache ccache
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: openwrt/.ccache
+  #         key: ccache-kernel-${{ env.TARGET }}/${{ env.SUBTARGET }}-${{ needs.determine_targets.outputs.ccache_hash }}
+  #         restore-keys: |
+  #           ccache-kernel-${{ env.TARGET }}/${{ env.SUBTARGET }}-
 
-      - name: Download external toolchain
-        if: ${{ steps.cache-external-toolchain.outputs.cache-hit != 'true' }}
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: |
-          wget -O - https://downloads.cdn.openwrt.org/snapshots/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${TOOLCHAIN_FILE}.tar.xz \
-            | tar --xz -xf -
+  #     - name: Download external toolchain
+  #       if: ${{ steps.cache-external-toolchain.outputs.cache-hit != 'true' }}
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: |
+  #         wget -O - https://downloads.cdn.openwrt.org/snapshots/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${TOOLCHAIN_FILE}.tar.xz \
+  #           | tar --xz -xf -
 
-      - name: Extract prebuilt tools
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: ./scripts/ext-tools.sh --tools /tools.tar
+  #     - name: Extract prebuilt tools
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: ./scripts/ext-tools.sh --tools /tools.tar
 
-      - name: Configure external toolchain
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: |
-          echo CONFIG_ALL_KMODS=y >> .config
-          echo CONFIG_DEVEL=y >> .config
-          echo CONFIG_AUTOREMOVE=y >> .config
-          echo CONFIG_CCACHE=y >> .config
+  #     - name: Configure external toolchain
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: |
+  #         echo CONFIG_ALL_KMODS=y >> .config
+  #         echo CONFIG_DEVEL=y >> .config
+  #         echo CONFIG_AUTOREMOVE=y >> .config
+  #         echo CONFIG_CCACHE=y >> .config
 
-          ./scripts/ext-toolchain.sh \
-            --toolchain ${{ env.TOOLCHAIN_FILE }}/toolchain-* \
-            --overwrite-config \
-            --config ${{ env.TARGET }}/${{ env.SUBTARGET }}
+  #         ./scripts/ext-toolchain.sh \
+  #           --toolchain ${{ env.TOOLCHAIN_FILE }}/toolchain-* \
+  #           --overwrite-config \
+  #           --config ${{ env.TARGET }}/${{ env.SUBTARGET }}
 
-      - name: Show configuration
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: ./scripts/diffconfig.sh
+  #     - name: Show configuration
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: ./scripts/diffconfig.sh
 
-      - name: Build tools
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: make tools/install -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
+  #     - name: Build tools
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: make tools/install -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
 
-      - name: Build toolchain
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: make toolchain/install -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
+  #     - name: Build toolchain
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: make toolchain/install -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
 
-      - name: Build Kernel
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: make target/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
+  #     - name: Build Kernel
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: make target/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
 
-      - name: Build Kernel Kmods
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: make package/linux/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
+  #     - name: Build Kernel Kmods
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: make package/linux/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
 
-      - name: Upload logs
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.TARGET }}-${{ env.SUBTARGET }}-logs
-          path: "openwrt/logs"
+  #     - name: Upload logs
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: ${{ env.TARGET }}-${{ env.SUBTARGET }}-logs
+  #         path: "openwrt/logs"
 
-  check-patch:
-    name: Check Kernel patches
-    needs: determine_targets
-    runs-on: ubuntu-latest
-    strategy:
-       fail-fast: False
-       matrix:
-         target: ${{fromJson(needs.determine_targets.outputs.target)}}
+  # check-patch:
+  #   name: Check Kernel patches
+  #   needs: determine_targets
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #      fail-fast: False
+  #      matrix:
+  #        target: ${{fromJson(needs.determine_targets.outputs.target)}}
 
-    container: ghcr.io/${{ needs.determine_targets.outputs.owner_lc }}/tools:latest
+  #   container: ghcr.io/${{ needs.determine_targets.outputs.owner_lc }}/tools:latest
 
-    permissions:
-      contents: read
-      packages: read
+  #   permissions:
+  #     contents: read
+  #     packages: read
 
-    steps:
-      - name: Checkout master directory
-        uses: actions/checkout@v3
-        with:
-          path: openwrt
+  #   steps:
+  #     - name: Checkout master directory
+  #       uses: actions/checkout@v3
+  #       with:
+  #         path: openwrt
 
-      - name: Fix permission
-        run: |
-          chown -R buildbot:buildbot openwrt
+  #     - name: Fix permission
+  #       run: |
+  #         chown -R buildbot:buildbot openwrt
 
-      - name: Initialization environment
-        run: |
-          TARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 1)
-          SUBTARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 2)
-          echo "TARGET=$TARGET" >> "$GITHUB_ENV"
-          echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
+  #     - name: Initialization environment
+  #       run: |
+  #         TARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 1)
+  #         SUBTARGET=$(echo ${{ matrix.target }} | cut -d "/" -f 2)
+  #         echo "TARGET=$TARGET" >> "$GITHUB_ENV"
+  #         echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
 
-      - name: Extract prebuilt tools
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: ./scripts/ext-tools.sh --tools /tools.tar
+  #     - name: Extract prebuilt tools
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: ./scripts/ext-tools.sh --tools /tools.tar
 
-      - name: Setup Config
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: |
-          echo CONFIG_ALL_KMODS=y >> .config
-          echo CONFIG_DEVEL=y >> .config
-          echo CONFIG_AUTOREMOVE=y >> .config
-          echo CONFIG_CCACHE=y >> .config
+  #     - name: Setup Config
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: |
+  #         echo CONFIG_ALL_KMODS=y >> .config
+  #         echo CONFIG_DEVEL=y >> .config
+  #         echo CONFIG_AUTOREMOVE=y >> .config
+  #         echo CONFIG_CCACHE=y >> .config
 
-          echo "CONFIG_TARGET_${{ env.TARGET }}=y" >> .config
-          echo "CONFIG_TARGET_${{ env.TARGET }}_${{ env.SUBTARGET }}=y" >> .config
+  #         echo "CONFIG_TARGET_${{ env.TARGET }}=y" >> .config
+  #         echo "CONFIG_TARGET_${{ env.TARGET }}_${{ env.SUBTARGET }}=y" >> .config
 
-          make defconfig
+  #         make defconfig
 
-      - name: Build tools
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: make tools/quilt/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
+  #     - name: Build tools
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: make tools/quilt/compile -j$(nproc) BUILD_LOG=1 || ret=$? .github/workflows/scripts/show_build_failures.sh
 
-      - name: Refresh Kernel patches
-        shell: su buildbot -c "sh -e {0}"
-        working-directory: openwrt
-        run: |
-          make target/linux/refresh V=s
+  #     - name: Refresh Kernel patches
+  #       shell: su buildbot -c "sh -e {0}"
+  #       working-directory: openwrt
+  #       run: |
+  #         make target/linux/refresh V=s
 
-          . .github/workflows/scripts/ci_helpers.sh
+  #         . .github/workflows/scripts/ci_helpers.sh
 
-          if git diff --name-only --exit-code; then
-            success "Kernel patches for ${{ env.TARGET }}/${{ env.SUBTARGET }} seems ok"
-          else
-            err "Kernel patches for ${{ env.TARGET }}/${{ env.SUBTARGET }} require refresh. (run 'make target/linux/refresh' and force push this pr)"
-            exit 1
-          fi
+  #         if git diff --name-only --exit-code; then
+  #           success "Kernel patches for ${{ env.TARGET }}/${{ env.SUBTARGET }} seems ok"
+  #         else
+  #           err "Kernel patches for ${{ env.TARGET }}/${{ env.SUBTARGET }} require refresh. (run 'make target/linux/refresh' and force push this pr)"
+  #           exit 1
+  #         fi
